version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
  sonarqube:
    image: sonarqube:9.9.1-community
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
      - '.\sonar\conf:/opt/sonarqube/conf'
      - '.\sonar\data:/opt/sonarqube/data'
      - '.\sonar\extensions:/opt/sonarqube/extensions'
      - '.\sonar\bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
